version: "3"

services:
  db:
    image: mysql:8
    restart: unless-stopped
    volumes:
      - ./DockerData/mysql:/var/lib/mysql:z
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: olivia
      MYSQL_ROOT_PASSWORD: password
